package com.wy.webprototype.dao;

import static com.wy.webprototype.util.AppContextWrapper.getEntityMgr;

import javax.persistence.EntityManager;

import com.wy.webprototype.model.User;

/**
 * The implementation will be combined in the UserDao proxy generated by Spring data JPA, just noted that
 * this kind of class defaults to have the suffix "Impl"
 * @author whitman.yang
 *
 */
public class UserDaoImpl implements CustomizedUserDao {
	
	public User customizedById(long userId) {
		EntityManager entityManager = getEntityMgr();
		return entityManager.find(User.class, userId);
	}

}
